name: GitHub Actions Security Analysis

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - ".github/workflows/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"

permissions: {}

jobs:
  zizmor:
    permissions:
      # read workflow runs and history
      actions: read
      # checkout repository contents
      contents: read
      # upload SARIF results to GitHub Security tab
      security-events: write
      # OIDC token for GitHub API authentication
      id-token: write
    uses: luxass/shared-workflows/.github/workflows/reusable-ci-security.yaml@dc5bd39f7ea1504fb0ff9745fbc65c629178d8b3 # v0.11.2
